### ISSUE TITLE
Tornado error 500 using conditional style

### ISSUE THREAD

**Issue by aalonzolu** [jobsta/reportbro-lib#8] opened 2019-11-28 22:13 UTC
Hi, when i'm using the community server my reports works well, but when i point the report to my own report server using the example reportbro_server.py i get this error.

```
reportbro_server   | ERROR:tornado.application:Uncaught exception PUT /reportbro/report/run (172.19.0.1)
reportbro_server   | HTTPServerRequest(protocol='http', host='local.geducar.com:8080', method='PUT', uri='/reportbro/report/run', version='HTTP/1.1', remote_ip='172.19.0.1')
reportbro_server   | Traceback (most recent call last):
reportbro_server   |   File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1699, in _execute
reportbro_server   |     result = await result
reportbro_server   | TypeError: object str can't be used in 'await' expression
reportbro_server   | ERROR:tornado.access:500 PUT /reportbro/report/run (172.19.0.1) 7.14ms

```

I get this error only when i use Conditional style, but with no conditional styles this works well.

**Comment by alhman** [comment] 2019-12-06 14:12
Hi, are you using the latest reportbro-lib 1.3.3? can you get more information about the actual error? I cannot reproduce this locally. Maybe it is related to Python 3.8 - have you tested with Python 3.6 or 3.7?

**Comment by alhman** [comment] 2020-03-06 13:03
Please post more information, otherwise I'll have to close this issue.

In the latest version there is a setting _menuShowDebug_ for the designer. If you set it to true then there is a menu button where you can output the whole report definition to the javascript console. Copy the whole report definition and upload it somewhere (e.g. pastebin). Then I can easily reproduce this error.

**Closed** 2020-04-20 14:20 UTC
