### ISSUE TITLE
Images in the section band broken

### ISSUE THREAD

**Issue by shyamjoshi** [jobsta/reportbro-lib#5] opened 2019-08-25 04:51 UTC
When trying to implement using images on the section band , the same image is repeated over and over again , instead of the image url provided in the list 

Steps to test 
1. create a section on the report 
2. add image widget 
3. To the data to source in the parameter add list 
4. in the list add textfield 
5. assign the text field to image widget as source 
6. assign the test data to the data source parameter 
7. preview 

adding the report requested with test data for testing on your end 
{"report":{"docElements":[{"elementType":"section","id":36,"containerId":"0_content","y":80,"label":"","dataSource":"${albums}","header":false,"footer":false,"printIf":"","headerData":{"elementType":"none","id":37,"containerId":"0_content","linkedContainerId":38,"height":100,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false,"repeatHeader":false},"contentData":{"elementType":"none","id":39,"containerId":"0_content","linkedContainerId":40,"height":400,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false},"footerData":{"elementType":"none","id":41,"containerId":"0_content","linkedContainerId":42,"height":100,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false}},{"elementType":"image","id":43,"containerId":40,"x":70,"y":40,"width":445,"height":290,"source":"${name}","image":"","imageFilename":"","horizontalAlignment":"left","verticalAlignment":"top","backgroundColor":"","printIf":"","removeEmptyElement":false,"link":"","spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_addEmptyRow":false},{"elementType":"text","id":47,"containerId":40,"x":90,"y":10,"width":100,"height":20,"content":"${name}","eval":false,"styleId":"","bold":false,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"left","verticalAlignment":"top","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":12,"lineSpacing":1,"borderColor":"#000000","borderWidth":1,"borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":2,"paddingTop":2,"paddingRight":2,"paddingBottom":2,"printIf":"","removeEmptyElement":false,"alwaysPrintOnSamePage":true,"pattern":"","link":"","cs_condition":"","cs_styleId":"","cs_bold":false,"cs_italic":false,"cs_underline":false,"cs_strikethrough":false,"cs_horizontalAlignment":"left","cs_verticalAlignment":"top","cs_textColor":"#000000","cs_backgroundColor":"","cs_font":"helvetica","cs_fontSize":12,"cs_lineSpacing":1,"cs_borderColor":"#000000","cs_borderWidth":"1","cs_borderAll":false,"cs_borderLeft":false,"cs_borderTop":false,"cs_borderRight":false,"cs_borderBottom":false,"cs_paddingLeft":2,"cs_paddingTop":2,"cs_paddingRight":2,"cs_paddingBottom":2,"spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_colspan":"","spreadsheet_addEmptyRow":false},{"elementType":"image","id":46,"containerId":"0_content","x":130,"y":0,"width":80,"height":80,"source":"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png","image":"","imageFilename":"","horizontalAlignment":"left","verticalAlignment":"top","backgroundColor":"","printIf":"","removeEmptyElement":false,"link":"","spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_addEmptyRow":false}],"parameters":[{"id":1,"name":"page_count","type":"number","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":true,"testData":""},{"id":2,"name":"page_number","type":"number","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":true,"testData":""},{"id":9,"name":"current_date","type":"date","arrayItemType":"string","eval":false,"nullable":false,"pattern":"d. MMMM yyyy, H:mm","expression":"","showOnlyNameType":false,"testData":""},{"id":10,"name":"year","type":"number","arrayItemType":"string","eval":false,"nullable":true,"pattern":"0","expression":"","showOnlyNameType":false,"testData":""},{"id":12,"name":"albums","type":"array","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":false,"testData":"[{\"name\":\"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png\"},{\"name\":\"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png\"},{\"name\":\"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png\"}]","children":[{"id":13,"name":"name","type":"string","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":false,"testData":""}]}],"styles":[{"id":33,"name":"Table Header","bold":true,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"center","verticalAlignment":"middle","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":"10","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"},{"id":34,"name":"Table Content","bold":false,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"left","verticalAlignment":"middle","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":"9","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"},{"id":35,"name":"Table Content Highlight","bold":true,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"center","verticalAlignment":"middle","textColor":"#3d85c6","backgroundColor":"","font":"helvetica","fontSize":"9","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"}],"version":2,"documentProperties":{"pageFormat":"A4","pageWidth":"","pageHeight":"","unit":"mm","orientation":"portrait","contentHeight":"","marginLeft":"10","marginTop":"10","marginRight":"10","marginBottom":"10","header":true,"headerSize":"80","headerDisplay":"always","footer":true,"footerSize":"30","footerDisplay":"always","patternLocale":"en","patternCurrencySymbol":"$"}},"outputFormat":"pdf","data":{"current_date":"","year":"","albums":[{"name":"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png"},{"name":"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png"},{"name":"https://i1076.photobucket.com/albums/w455/shyamjoshi/Screen%20Shot%202019-08-19%20at%203.43.14%20PM_zps1l4qpice.png"}]},"isTestData":true}

**Comment by shyamjoshi** [comment] 2019-08-25 05:01
`{"report":{"docElements":[{"elementType":"section","id":36,"containerId":"0_content","y":80,"label":"","dataSource":"${albums}","header":false,"footer":false,"printIf":"","headerData":{"elementType":"none","id":37,"containerId":"0_content","linkedContainerId":38,"height":100,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false,"repeatHeader":false},"contentData":{"elementType":"none","id":39,"containerId":"0_content","linkedContainerId":40,"height":400,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false},"footerData":{"elementType":"none","id":41,"containerId":"0_content","linkedContainerId":42,"height":100,"alwaysPrintOnSamePage":true,"shrinkToContentHeight":false}},{"elementType":"image","id":43,"containerId":40,"x":70,"y":40,"width":445,"height":290,"source":"${name}","image":"","imageFilename":"","horizontalAlignment":"left","verticalAlignment":"top","backgroundColor":"","printIf":"","removeEmptyElement":false,"link":"","spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_addEmptyRow":false},{"elementType":"text","id":47,"containerId":40,"x":90,"y":10,"width":100,"height":20,"content":"${name}","eval":false,"styleId":"","bold":false,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"left","verticalAlignment":"top","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":12,"lineSpacing":1,"borderColor":"#000000","borderWidth":1,"borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":2,"paddingTop":2,"paddingRight":2,"paddingBottom":2,"printIf":"","removeEmptyElement":false,"alwaysPrintOnSamePage":true,"pattern":"","link":"","cs_condition":"","cs_styleId":"","cs_bold":false,"cs_italic":false,"cs_underline":false,"cs_strikethrough":false,"cs_horizontalAlignment":"left","cs_verticalAlignment":"top","cs_textColor":"#000000","cs_backgroundColor":"","cs_font":"helvetica","cs_fontSize":12,"cs_lineSpacing":1,"cs_borderColor":"#000000","cs_borderWidth":"1","cs_borderAll":false,"cs_borderLeft":false,"cs_borderTop":false,"cs_borderRight":false,"cs_borderBottom":false,"cs_paddingLeft":2,"cs_paddingTop":2,"cs_paddingRight":2,"cs_paddingBottom":2,"spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_colspan":"","spreadsheet_addEmptyRow":false},{"elementType":"image","id":46,"containerId":"0_content","x":130,"y":0,"width":80,"height":80,"source":"http://carmel-general-forms.dira2.co.il//Model_Products/4f27903b3a95d9846b5c3280fb6e6d0a.jpg","image":"","imageFilename":"","horizontalAlignment":"left","verticalAlignment":"top","backgroundColor":"","printIf":"","removeEmptyElement":false,"link":"","spreadsheet_hide":false,"spreadsheet_column":"","spreadsheet_addEmptyRow":false}],"parameters":[{"id":1,"name":"page_count","type":"number","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":true,"testData":""},{"id":2,"name":"page_number","type":"number","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":true,"testData":""},{"id":9,"name":"current_date","type":"date","arrayItemType":"string","eval":false,"nullable":false,"pattern":"d. MMMM yyyy, H:mm","expression":"","showOnlyNameType":false,"testData":""},{"id":10,"name":"year","type":"number","arrayItemType":"string","eval":false,"nullable":true,"pattern":"0","expression":"","showOnlyNameType":false,"testData":""},{"id":12,"name":"albums","type":"array","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":false,"testData":"[{\"name\":\"http://carmel-general-forms.dira2.co.il//Model_Products/4f27903b3a95d9846b5c3280fb6e6d0a.jpg\"},{\"name\":\"http://carmel-general-forms.dira2.co.il//Model_Products/eb98829fb0b3e7adbcec6ce76f9e6c89.jpg\"},{\"name\":\"http://carmel-general-forms.dira2.co.il//Model_Products/4f27903b3a95d9846b5c3280fb6e6d0a.jpg\"},{\"name\":\"http://carmel-general-forms.dira2.co.il//Model_Products/eb98829fb0b3e7adbcec6ce76f9e6c89.jpg\"}]","children":[{"id":13,"name":"name","type":"string","arrayItemType":"string","eval":false,"nullable":false,"pattern":"","expression":"","showOnlyNameType":false,"testData":""}]}],"styles":[{"id":33,"name":"Table Header","bold":true,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"center","verticalAlignment":"middle","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":"10","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"},{"id":34,"name":"Table Content","bold":false,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"left","verticalAlignment":"middle","textColor":"#000000","backgroundColor":"","font":"helvetica","fontSize":"9","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"},{"id":35,"name":"Table Content Highlight","bold":true,"italic":false,"underline":false,"strikethrough":false,"horizontalAlignment":"center","verticalAlignment":"middle","textColor":"#3d85c6","backgroundColor":"","font":"helvetica","fontSize":"9","lineSpacing":1,"borderColor":"#000000","borderWidth":"1","borderAll":false,"borderLeft":false,"borderTop":false,"borderRight":false,"borderBottom":false,"paddingLeft":"2","paddingTop":"2","paddingRight":"2","paddingBottom":"2"}],"version":2,"documentProperties":{"pageFormat":"A4","pageWidth":"","pageHeight":"","unit":"mm","orientation":"portrait","contentHeight":"","marginLeft":"10","marginTop":"10","marginRight":"10","marginBottom":"10","header":true,"headerSize":"80","headerDisplay":"always","footer":true,"footerSize":"30","footerDisplay":"always","patternLocale":"en","patternCurrencySymbol":"$"}},"outputFormat":"pdf","data":{"current_date":"","year":"","albums":[{"name":"http://carmel-general-forms.dira2.co.il//Model_Products/4f27903b3a95d9846b5c3280fb6e6d0a.jpg"},{"name":"http://carmel-general-forms.dira2.co.il//Model_Products/eb98829fb0b3e7adbcec6ce76f9e6c89.jpg"},{"name":"http://carmel-general-forms.dira2.co.il//Model_Products/4f27903b3a95d9846b5c3280fb6e6d0a.jpg"},{"name":"http://carmel-general-forms.dira2.co.il//Model_Products/eb98829fb0b3e7adbcec6ce76f9e6c89.jpg"}]},"isTestData":true}`


I am trying to solve it , as i understand at this point the imageElement , is one object even inside the container , same with text , the only reason why textElement works properly is we already print in the prepare section , same does not happen with the image element.


According to what i see the first image gets printed always, and since i am new to this code , i have not been able to resolve this problem any help would be appriciated

**Comment by shyamjoshi** [comment] 2019-08-26 09:10
I have a possible solution , isnt the most ideal solution but with my limited understanding , this should work

**Comment by alhman** [comment] 2019-08-28 10:03
We can reproduce the issue. It's a little bit more complicated so a fix will take some time. Problem is that ImageElement.get_next_render_element returns the same instance, therefor when the images are rendered the last state is used.

**Comment by shyamjoshi** [comment] 2019-08-28 10:30
hi , it seems it does not effect text , becuase text renders in prepare itself , i am able to solve this problem , on my code forgot to commit the last part , i will commit it and hope that it helps you to solve this faster

**Comment by alhman** [comment] 2019-08-28 10:33
Texts are not affected because TextElement.get_next_render_element returns new elements for rendering.

**Comment by shyamjoshi** [comment] 2019-08-28 10:40
ok , that makes sense .  this code is amazing you , guys have done amazing work. I was able to solve this issue on my end , by resetting the image and simply cloning the new image object. 

i see that you dont have ImageElement.get_next_render_element on the code itself.

thanks for the response , when you have finished i would prefer to merge your code (which probably would be better then mine )

**Comment by alhman** [comment] 2019-09-03 10:47
thanks, the rendering issues are now fixed in the latest release v1.3.1

**Closed by alhman** 2019-09-03 10:47 UTC
